services:
  conduit:
    image: "conduit:${CONDUIT_RELEASE:-development}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONDUIT_RELEASE: "${CONDUIT_RELEASE:-development}"
