import {
  formatShortcutBinding, shortcutBinding, shortcutStroke,
} from "../shortcuts/shortcut-normalize.ts";
import { detectShortcutEnvironment } from "../shortcuts/shortcut-environment.ts";
import type {
  ShortcutBinding, ShortcutCommandDefinition, ShortcutEnvironment, ShortcutModifier,
} from "../shortcuts/shortcut-types.ts";

const stroke = (code: string, key: string, modifiers: ShortcutModifier[] = []) =>
  shortcutStroke(code, key, modifiers);
const binding = (...strokes: ReturnType<typeof stroke>[]) => shortcutBinding(...strokes);

export const COMMAND_IDS = {
  openCommandPalette: "open-command-palette",
  searchChats: "search-chats",
  openSettings: "open-settings",
  openWorkspaceViews: "open-workspace-views",
  newChat: "new-chat",
  newFolder: "new-folder",
  newWorkspace: "new-workspace",
  openRuntimeChat: "runtime-chat",
  attachFiles: "attach",
  toggleSidebar: "toggle-sidebar",
  toggleWorkspacePanel: "toggle-workspace-panel",
  copyTranscript: "copy-transcript",
  renameChat: "rename",
  moveChat: "move",
  renameFolder: "rename-folder",
  stopResponse: "stop",
  regenerateResponse: "regenerate",
  continueResponse: "continue",
  copyResponse: "copy",
  retryConnection: "retry-connection",
  reload: "reload",
  deleteChat: "delete",
  deleteFolder: "delete-folder",
  logout: "logout",
  toggleChatEdit: "chat-search.toggle-edit",
  renameHighlightedChat: "chat-search.rename-highlighted",
  moveHighlightedChat: "chat-search.move-highlighted",
  deleteHighlightedChat: "chat-search.delete-highlighted",
  moveSelectedChats: "chat-search.move-selected",
  deleteSelectedChats: "chat-search.delete-selected",
} as const;

const command = (
  definition: Omit<ShortcutCommandDefinition, "defaultBindings" | "configurable"> & {
    defaultBindings?: ShortcutBinding[];
    configurable?: boolean;
  },
): ShortcutCommandDefinition => ({
  defaultBindings: [],
  configurable: true,
  ...definition,
});

export const commandRegistry: ShortcutCommandDefinition[] = [
  command({
    id: COMMAND_IDS.openCommandPalette,
    label: "Open command palette",
    description: "Browse and run Conduit commands",
    group: "commands",
    icon: "search",
    keywords: ["command", "palette", "search", "actions"],
    contexts: ["application"],
    defaultBindings: [binding(stroke("KeyK", "K", ["primary"]))],
  }),
  command({
    id: COMMAND_IDS.searchChats,
    label: "Search chats…",
    description: "Find and manage chats across folders and workspaces",
    group: "commands",
    icon: "chat",
    keywords: ["search", "find", "chat", "conversation", "folder", "workspace"],
    contexts: ["application", "palette.root", "palette.page"],
    defaultBindings: [
      binding(stroke("KeyP", "P", ["primary"])),
      binding(stroke("KeyO", "O", ["primary", "shift"])),
    ],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.openSettings,
    label: "Settings…",
    description: "Configure models, runtime, and preferences",
    group: "commands",
    icon: "settings",
    keywords: ["preferences", "configure"],
    contexts: ["application", "palette.root", "palette.page"],
    defaultBindings: [binding(stroke("Comma", ",", ["primary"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.openWorkspaceViews,
    label: "Workspace views…",
    description: "Open files, source control, artifacts, or a terminal",
    group: "commands",
    icon: "workspace-panel",
    keywords: ["workspace", "files", "source control", "artifacts", "terminal", "shell"],
    contexts: ["palette.root", "palette.page"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.logout,
    label: "Sign out",
    description: "Ends this browser's Conduit session",
    group: "danger",
    icon: "logout",
    keywords: ["logout", "sign out", "session", "auth"],
    contexts: ["palette.root"],
    destructive: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.newChat,
    label: "New chat",
    description: "Start a chat in the current folder",
    group: "commands",
    icon: "new-chat",
    keywords: ["create", "conversation"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("KeyC", "C", ["primary", "shift"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.newFolder,
    label: "New folder",
    description: "Create a managed working directory and chat scope",
    group: "commands",
    icon: "new-folder",
    keywords: ["project", "create", "directory", "folder"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.newWorkspace,
    label: "New workspace",
    description: "Link an existing directory or clone a repository",
    group: "commands",
    icon: "new-folder",
    keywords: ["project", "create", "directory", "workspace", "clone", "link"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.openRuntimeChat,
    label: "Open runtime chat",
    description: "Admin chat for templates and Pi packages",
    group: "commands",
    icon: "profile",
    keywords: ["admin", "template", "plugin", "install", "runtime"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.attachFiles,
    label: "Attach files",
    description: "Upload files to this chat",
    group: "commands",
    icon: "attach",
    keywords: ["upload", "file"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleSidebar,
    label: "Toggle sidebar",
    description: "Show or hide the navigation sidebar",
    group: "commands",
    icon: "sidebar",
    keywords: ["panel", "nav", "menu"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("KeyB", "B", ["primary"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleWorkspacePanel,
    label: "Toggle workspace panel",
    description: "Browse project files and working-tree changes",
    group: "commands",
    icon: "workspace-panel",
    keywords: ["files", "diff", "inspector", "right panel"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("Period", ".", ["primary"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.copyTranscript,
    label: "Copy transcript",
    description: "Copy the full chat transcript",
    group: "commands",
    icon: "copy-transcript",
    keywords: ["clipboard", "export", "full"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.renameChat,
    label: "Rename chat",
    description: "Change this chat's title",
    group: "commands",
    icon: "rename",
    keywords: ["title"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.moveChat,
    label: "Move chat",
    description: "Move this chat to another folder",
    group: "commands",
    icon: "move",
    keywords: ["folder", "project"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.renameFolder,
    label: "Rename folder",
    description: "Change the current folder's display name",
    group: "commands",
    icon: "rename",
    keywords: ["project", "title"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.stopResponse,
    label: "Stop response",
    description: "Freeze and abort the current response",
    group: "commands",
    icon: "stop",
    keywords: ["abort", "cancel"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.regenerateResponse,
    label: "Regenerate last response",
    description: "Fork and ask the last question again",
    group: "commands",
    icon: "regenerate",
    keywords: ["retry"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.continueResponse,
    label: "Continue stopped response",
    description: "Experimentally continue the last partial answer",
    group: "commands",
    icon: "continue",
    keywords: ["resume"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.copyResponse,
    label: "Copy last response",
    description: "Copy source Markdown",
    group: "commands",
    icon: "copy",
    keywords: ["clipboard", "markdown"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.retryConnection,
    label: "Retry connection",
    description: "Reconnect to the Conduit server",
    group: "commands",
    icon: "retry",
    keywords: ["reconnect", "offline", "server"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.reload,
    label: "Reload Conduit",
    description: "Refresh the application",
    group: "commands",
    icon: "reload",
    keywords: ["refresh", "restart"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.deleteChat,
    label: "Delete chat",
    description: "Permanently delete this chat and its files",
    group: "danger",
    icon: "delete",
    keywords: ["remove", "trash"],
    contexts: ["palette.root"],
    destructive: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.deleteFolder,
    label: "Delete folder",
    description: "Permanently delete this folder and its chats",
    group: "danger",
    icon: "delete",
    keywords: ["remove", "trash", "project"],
    contexts: ["palette.root"],
    destructive: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleChatEdit,
    label: "Edit chats",
    description: "Enter or leave bulk chat selection",
    group: "chat-management",
    icon: "chat",
    keywords: ["select", "bulk", "manage", "done"],
    contexts: ["chat-search.browse", "chat-search.edit"],
    defaultBindings: [binding(stroke("KeyE", "E", ["primary"]))],
  }),
  command({
    id: COMMAND_IDS.renameHighlightedChat,
    label: "Rename highlighted chat",
    description: "Change the highlighted chat title",
    group: "chat-management",
    icon: "rename",
    keywords: ["rename", "title", "highlighted"],
    contexts: ["chat-search.browse"],
    defaultBindings: [
      binding(stroke("KeyR", "R", ["alt"])),
      binding(stroke("KeyK", "K", ["primary"]), stroke("KeyR", "R")),
    ],
  }),
  command({
    id: COMMAND_IDS.moveHighlightedChat,
    label: "Move highlighted chat",
    description: "Move the highlighted chat to another folder",
    group: "chat-management",
    icon: "move",
    keywords: ["move", "folder", "highlighted"],
    contexts: ["chat-search.browse"],
    defaultBindings: [
      binding(stroke("KeyK", "K", ["primary"]), stroke("KeyM", "M")),
    ],
  }),
  command({
    id: COMMAND_IDS.deleteHighlightedChat,
    label: "Delete highlighted chat",
    description: "Delete the highlighted chat after confirmation",
    group: "chat-management",
    icon: "delete",
    keywords: ["delete", "remove", "highlighted"],
    contexts: ["chat-search.browse"],
    defaultBindings: [
      binding(stroke("KeyK", "K", ["primary"]), stroke("KeyD", "D")),
    ],
    destructive: true,
  }),
  command({
    id: COMMAND_IDS.moveSelectedChats,
    label: "Move selected chats",
    description: "Move all selected chats to another folder",
    group: "chat-management",
    icon: "move",
    keywords: ["move", "bulk", "selected"],
    contexts: ["chat-search.edit"],
    defaultBindings: [binding(stroke("KeyM", "M"))],
  }),
  command({
    id: COMMAND_IDS.deleteSelectedChats,
    label: "Delete selected chats",
    description: "Delete all selected chats after confirmation",
    group: "chat-management",
    icon: "delete",
    keywords: ["delete", "remove", "bulk", "selected"],
    contexts: ["chat-search.edit"],
    defaultBindings: [
      binding(stroke("KeyD", "D")),
      binding(stroke("Delete", "Delete")),
    ],
    destructive: true,
  }),
];

const commandById = new Map(commandRegistry.map((definition) => [definition.id, definition]));

export function getCommandDefinition(commandId: string): ShortcutCommandDefinition {
  const definition = commandById.get(commandId);
  if (!definition) throw new Error(`Unknown command: ${commandId}`);
  return definition;
}

export function commandDefaultBindings(commandId: string): ShortcutBinding[] {
  return getCommandDefinition(commandId).defaultBindings;
}

export function commandDefaultShortcut(
  commandId: string,
  environment: ShortcutEnvironment = detectShortcutEnvironment(),
): string | null {
  const bindingValue = commandDefaultBindings(commandId)[0];
  return bindingValue ? formatShortcutBinding(bindingValue, environment) : null;
}

export const paletteStableCommandIds = commandRegistry
  .filter((definition) => definition.palette)
  .map((definition) => definition.id);
