import {
  shortcutBinding, shortcutStroke,
} from "../shortcuts/shortcut-normalize.ts";
import type {
  ShortcutBinding, ShortcutCommandDefinition, ShortcutModifier,
} from "../shortcuts/shortcut-types.ts";

const stroke = (code: string, key: string, modifiers: ShortcutModifier[] = []) =>
  shortcutStroke(code, key, modifiers);
const binding = (...strokes: ReturnType<typeof stroke>[]) => shortcutBinding(...strokes);
/** The leader: Ctrl+G ("go"), clear of Cut; its browser use, Find next, gives way to the page. */
export const LEADER_STROKE = stroke("KeyG", "G", ["primary"]);
const scopedBinding = (code: string, key: string, modifiers: ShortcutModifier[] = []) =>
  binding(LEADER_STROKE, stroke(code, key, modifiers));
// Go-to shortcuts: one chord per top-level surface, numbered in screen order.
// They open a closed surface and focus it, and never close one -- Ctrl+B and
// Ctrl+. stay the toggles. The leader acts within a region; it does not move
// between them.
const goTo = (digit: number) => binding(stroke(`Digit${digit}`, String(digit), ["primary", "shift"]));
const EVERY_REGION = ["application", "chat", "dashboard", "workspace-panel"];

export const COMMAND_IDS = {
  openCommandPalette: "open-command-palette",
  searchChats: "search-chats",
  openSettings: "open-settings",
  openModelSelector: "open-model-selector",
  toggleModelScope: "model-selector.toggle-scope",
  openWorkspaceViews: "open-workspace-views",
  newChat: "new-chat",
  newFolder: "new-folder",
  newWorkspace: "new-workspace",
  openRuntimeChat: "runtime-chat",
  attachFiles: "attach",
  stashPrompt: "stash-prompt",
  toggleDictation: "voice-dictation",
  toggleSidebar: "toggle-sidebar",
  toggleWorkspacePanel: "toggle-workspace-panel",
  maximizeWorkspacePanel: "maximize-workspace-panel",
  focusComposer: "focus-composer",
  focusSidebar: "focus-sidebar",
  focusMainPane: "focus-main-pane",
  focusTranscript: "focus-transcript",
  focusWorkspacePanel: "focus-workspace-panel",
  toggleChatWorkspaceFocus: "toggle-chat-workspace-focus",
  workspaceFiles: "workspace-panel.files",
  workspaceSourceControl: "workspace-panel.source-control",
  workspaceChat: "workspace-panel.artifacts",
  // Persistent alias for existing shortcut settings.
  workspaceArtifacts: "workspace-panel.artifacts",
  workspaceTerminal: "workspace-panel.terminal",
  workspaceSplit: "workspace-panel.split",
  copyTranscript: "copy-transcript",
  renameChat: "rename",
  autoNameChat: "rename-from-context",
  moveChat: "move",
  renameFolder: "rename-folder",
  stopResponse: "stop",
  stopProcess: "stop-process",
  regenerateResponse: "regenerate",
  continueResponse: "continue",
  compactContext: "compact-context",
  copyResponse: "copy",
  retryConnection: "retry-connection",
  reload: "reload",
  updateApp: "update-app",
  resetAppCache: "reset-app-cache",
  keyboardProbe: "keyboard-probe",
  deleteChat: "delete",
  deleteFolder: "delete-folder",
  logout: "logout",
  revealWindow: "desktop.reveal",
  newChatGlobally: "desktop.new-chat",
  toggleChatEdit: "chat-search.toggle-edit",
  renameHighlightedChat: "chat-search.rename-highlighted",
  moveHighlightedChat: "chat-search.move-highlighted",
  deleteHighlightedChat: "chat-search.delete-highlighted",
  moveSelectedChats: "chat-search.move-selected",
  deleteSelectedChats: "chat-search.delete-selected",
} as const;

const command = (
  definition: Omit<ShortcutCommandDefinition, "defaultBindings" | "configurable"> & {
    defaultBindings?: ShortcutBinding[];
    configurable?: boolean;
  },
): ShortcutCommandDefinition => ({
  defaultBindings: [],
  configurable: true,
  ...definition,
});

export const commandRegistry: ShortcutCommandDefinition[] = [
  command({
    id: COMMAND_IDS.openCommandPalette,
    label: "Open command palette",
    description: "Browse and run Conduit commands",
    group: "commands",
    icon: "search",
    keywords: ["command", "palette", "search", "actions"],
    contexts: ["application"],
    defaultBindings: [binding(stroke("KeyK", "K", ["primary"]))],
  }),
  command({
    id: COMMAND_IDS.searchChats,
    label: "Search chats…",
    description: "Find and manage chats across folders and workspaces",
    group: "commands",
    icon: "chat",
    keywords: ["search", "find", "chat", "conversation", "folder", "workspace"],
    contexts: [
      "application", "palette.root", "palette.page", "chat-search.browse",
      "chat-search.edit", "chat-search.move", "chat-search.rename",
    ],
    defaultBindings: [binding(stroke("KeyK", "K", ["primary", "shift"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.openSettings,
    label: "Settings…",
    description: "Configure models, runtime, and preferences",
    group: "commands",
    icon: "settings",
    keywords: ["preferences", "configure"],
    contexts: ["application", "palette.root", "palette.page"],
    defaultBindings: [binding(stroke("Comma", ",", ["primary"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.openModelSelector,
    label: "Model selector…",
    description: "Choose the models available in this project",
    group: "commands",
    icon: "model",
    keywords: ["model", "models", "provider", "scope", "enable"],
    contexts: ["application", "model-selector"],
    defaultBindings: [binding(stroke("KeyX", "X", ["primary", "shift"]))],
  }),
  command({
    id: COMMAND_IDS.toggleModelScope,
    label: "Add or remove scoped model",
    description: "Add or remove the highlighted model from the project scope",
    group: "commands",
    icon: "model",
    keywords: ["model", "scope", "enable", "disable"],
    contexts: ["model-selector"],
    defaultBindings: [binding(stroke("KeyF", "F", ["primary"]))],
  }),
  command({
    id: COMMAND_IDS.openWorkspaceViews,
    label: "Workspace views…",
    description: "Open files, source control, chat details, or a terminal",
    group: "commands",
    icon: "workspace-panel",
    keywords: ["workspace", "files", "source control", "chat", "history", "artifacts", "terminal", "shell"],
    contexts: ["palette.root", "palette.page"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.logout,
    label: "Sign out",
    description: "Ends this browser's Conduit session",
    group: "danger",
    icon: "logout",
    keywords: ["logout", "sign out", "session", "auth"],
    contexts: ["palette.root"],
    destructive: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.newChat,
    label: "New chat",
    description: "Start a chat in the current folder",
    group: "commands",
    icon: "new-chat",
    keywords: ["create", "conversation"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("KeyC", "C", ["primary", "shift"]))],
    palette: true,
  }),
  // The two system-wide commands. They are separate definitions rather than a
  // global scope added to their in-window twins, because every binding on a
  // command in this scope is taken from the OS: giving New chat the scope would
  // have claimed Ctrl+Shift+C from every other application. The defaults use
  // Alt+Shift, which no browser or Windows shell shortcut occupies, and either
  // can be rebound or cleared in Settings like any other.
  command({
    id: COMMAND_IDS.revealWindow,
    label: "Open Conduit",
    description: "Bring the window forward from anywhere, even when Conduit is hidden",
    group: "desktop",
    icon: "window",
    keywords: ["show", "reveal", "focus", "global", "system", "desktop", "tray"],
    contexts: ["global"],
    defaultBindings: [binding(stroke("KeyC", "C", ["alt", "shift"]))],
  }),
  command({
    id: COMMAND_IDS.newChatGlobally,
    label: "New chat from anywhere",
    description: "Open Conduit and start a chat without leaving what you are doing",
    group: "desktop",
    icon: "new-chat",
    keywords: ["create", "conversation", "global", "system", "desktop"],
    contexts: ["global"],
    defaultBindings: [binding(stroke("KeyN", "N", ["alt", "shift"]))],
  }),
  command({
    id: COMMAND_IDS.newFolder,
    label: "New folder",
    description: "Create a managed working directory and chat scope",
    group: "commands",
    icon: "new-folder",
    keywords: ["project", "create", "directory", "folder"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.newWorkspace,
    label: "New workspace",
    description: "Link an existing directory or clone a repository",
    group: "commands",
    icon: "new-folder",
    keywords: ["project", "create", "directory", "workspace", "clone", "link"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.openRuntimeChat,
    label: "Open runtime chat",
    description: "Admin chat for templates and runtime packages",
    group: "commands",
    icon: "profile",
    keywords: ["admin", "template", "plugin", "install", "runtime"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.stashPrompt,
    label: "Stash prompt",
    description: "Park the current prompt, or restore the last one you parked",
    group: "commands",
    icon: "attach",
    keywords: ["stash", "draft", "park", "save", "restore", "prompt"],
    contexts: ["chat", "dashboard", "palette.root"],
    // Plain mod+S is the browser's Save Page. Rebind it in Settings if you
    // would rather have the shorter key and can live with intercepting it.
    defaultBindings: [binding(stroke("KeyS", "S", ["primary", "shift"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.attachFiles,
    label: "Attach files",
    description: "Upload files to this chat",
    group: "commands",
    icon: "attach",
    keywords: ["upload", "file"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleDictation,
    label: "Toggle voice dictation",
    description: "Start or stop dictation in the composer",
    group: "commands",
    icon: "microphone",
    keywords: ["voice", "microphone", "speech", "push to talk", "transcribe"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleSidebar,
    label: "Toggle sidebar",
    description: "Show or hide the navigation sidebar",
    group: "commands",
    icon: "sidebar",
    keywords: ["panel", "nav", "menu"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("KeyB", "B", ["primary"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleWorkspacePanel,
    label: "Toggle workspace panel",
    description: "Browse project files and working-tree changes",
    group: "commands",
    icon: "workspace-panel",
    keywords: ["files", "diff", "inspector", "right panel"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("Period", ".", ["primary"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.maximizeWorkspacePanel,
    label: "Toggle maximized workspace panel",
    description: "Open the workspace panel full width or close it",
    group: "commands",
    icon: "workspace-panel",
    keywords: ["files", "workspace", "maximize", "full width"],
    contexts: ["application", "palette.root"],
    defaultBindings: [binding(stroke("Period", ".", ["primary", "shift"]))],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.focusComposer,
    label: "Focus composer",
    description: "Place the cursor in the message composer",
    group: "navigation",
    icon: "chat",
    keywords: ["chat", "message", "input", "cursor"],
    contexts: EVERY_REGION,
    allowInExclusiveTarget: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.focusSidebar,
    label: "Go to sidebar",
    description: "Open the sidebar if it is closed and focus it, at the current row",
    group: "navigation",
    icon: "sidebar",
    keywords: ["sidebar", "focus", "navigate", "chats", "projects", "go to"],
    contexts: ["application"],
    defaultBindings: [goTo(1)],
    allowInExclusiveTarget: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.focusMainPane,
    label: "Go to main pane",
    description: "Move focus to the chat or dashboard, at its composer",
    group: "navigation",
    icon: "chat",
    keywords: ["chat", "dashboard", "main", "focus", "composer"],
    contexts: ["application"],
    defaultBindings: [goTo(2)],
    allowInExclusiveTarget: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.focusTranscript,
    label: "Go to transcript",
    description: "Move focus to the chat transcript, to scroll it from the keyboard",
    group: "navigation",
    icon: "chat",
    keywords: ["transcript", "messages", "scroll", "focus", "read"],
    contexts: EVERY_REGION,
    allowInExclusiveTarget: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.focusWorkspacePanel,
    label: "Focus workspace panel",
    description: "Open the workspace panel if it is closed and focus it",
    group: "navigation",
    icon: "workspace-panel",
    keywords: ["workspace", "panel", "focus", "files", "go to"],
    contexts: EVERY_REGION,
    defaultBindings: [goTo(3)],
    allowInExclusiveTarget: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleChatWorkspaceFocus,
    label: "Switch chat/workspace focus",
    description: "Move focus between the chat and open workspace panel",
    group: "navigation",
    icon: "workspace-panel",
    keywords: ["focus", "chat", "workspace", "panel", "switch"],
    contexts: ["application", "chat", "dashboard", "workspace-panel"],
    allowInExclusiveTarget: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.workspaceFiles,
    label: "Open workspace Files tab",
    description: "Show project files in the open workspace panel",
    group: "workspace-panel",
    icon: "workspace-panel",
    keywords: ["workspace", "files", "tree", "tab"],
    contexts: ["workspace-panel"],
    defaultBindings: [scopedBinding("Digit1", "1")],
    allowInExclusiveTarget: true,
  }),
  command({
    id: COMMAND_IDS.workspaceSourceControl,
    label: "Open workspace Source Control tab",
    description: "Show working-tree changes in the open workspace panel",
    group: "workspace-panel",
    icon: "workspace-panel",
    keywords: ["workspace", "git", "diff", "source control", "tab"],
    contexts: ["workspace-panel"],
    defaultBindings: [scopedBinding("Digit2", "2")],
    allowInExclusiveTarget: true,
  }),
  command({
    id: COMMAND_IDS.workspaceChat,
    label: "Open workspace Chat tab",
    description: "Show chat history, agent changes, and outputs in the open workspace panel",
    group: "workspace-panel",
    icon: "workspace-panel",
    keywords: ["workspace", "chat", "history", "agent changes", "artifacts", "outputs", "tab"],
    contexts: ["workspace-panel"],
    defaultBindings: [scopedBinding("Digit3", "3")],
    allowInExclusiveTarget: true,
  }),
  command({
    id: COMMAND_IDS.workspaceTerminal,
    label: "Open workspace Terminal tab",
    description: "Show the terminal in the open workspace panel",
    group: "workspace-panel",
    icon: "terminal",
    keywords: ["workspace", "terminal", "shell", "tab"],
    contexts: ["workspace-panel"],
    defaultBindings: [scopedBinding("Digit4", "4")],
    allowInExclusiveTarget: true,
  }),
  command({
    id: COMMAND_IDS.workspaceSplit,
    label: "Toggle workspace split pane",
    description: "Open or close the second pane of the maximized workspace panel",
    group: "workspace-panel",
    icon: "workspace-panel",
    keywords: ["workspace", "split", "pane", "side by side"],
    contexts: ["workspace-panel"],
    defaultBindings: [scopedBinding("Backslash", "\\")],
    allowInExclusiveTarget: true,
  }),
  command({
    id: COMMAND_IDS.copyTranscript,
    label: "Copy transcript",
    description: "Copy the full chat transcript",
    group: "commands",
    icon: "copy-transcript",
    keywords: ["clipboard", "export", "full"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.renameChat,
    label: "Rename chat",
    description: "Change this chat's title",
    group: "commands",
    icon: "rename",
    keywords: ["title"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.autoNameChat,
    label: "Regenerate name",
    description: "Generate a new title from the current full chat context",
    group: "commands",
    icon: "rename",
    keywords: ["title", "name", "generate", "regenerate", "rename", "context", "automatic"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.moveChat,
    label: "Move chat",
    description: "Move this chat to another folder",
    group: "commands",
    icon: "move",
    keywords: ["folder", "project"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.renameFolder,
    label: "Rename folder",
    description: "Change the current folder's display name",
    group: "commands",
    icon: "rename",
    keywords: ["project", "title"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.stopResponse,
    label: "Stop response",
    description: "Freeze and abort the current response",
    group: "commands",
    icon: "stop",
    keywords: ["abort", "cancel"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.stopProcess,
    label: "Stop process",
    description: "Release Conduit's process and keep the chat",
    group: "commands",
    icon: "stop",
    keywords: ["disconnect", "release", "unsubscribe", "runtime"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.regenerateResponse,
    label: "Regenerate last response",
    description: "Fork and ask the last question again",
    group: "commands",
    icon: "regenerate",
    keywords: ["retry"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.continueResponse,
    label: "Continue stopped response",
    description: "Experimentally continue the last partial answer",
    group: "commands",
    icon: "continue",
    keywords: ["resume"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.compactContext,
    label: "Compact context",
    description: "Summarize older context to make room for more work",
    group: "commands",
    icon: "chat",
    keywords: ["summarize", "tokens", "context"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.copyResponse,
    label: "Copy last response",
    description: "Copy source Markdown",
    group: "commands",
    icon: "copy",
    keywords: ["clipboard", "markdown"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.retryConnection,
    label: "Retry connection",
    description: "Reconnect to the Conduit server",
    group: "commands",
    icon: "retry",
    keywords: ["reconnect", "offline", "server"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.reload,
    label: "Reload Conduit",
    description: "Refresh the application",
    group: "commands",
    icon: "reload",
    keywords: ["refresh", "restart"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.updateApp,
    label: "Update app",
    description: "Check for a new app version and reload",
    group: "commands",
    icon: "reload",
    keywords: ["update", "refresh", "pwa", "service worker", "cache", "stale"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.keyboardProbe,
    label: "Show keyboard measurements",
    // Reachable from the palette because the Android shell has no address bar
    // to put a flag in, and this is the one client the numbers are needed from.
    description: "Overlay the viewport numbers behind the on-screen keyboard",
    group: "commands",
    icon: "reload",
    keywords: ["keyboard", "viewport", "diagnostic", "probe", "debug"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.resetAppCache,
    label: "Reset app cache",
    description: "Remove cached app files and reload",
    group: "commands",
    icon: "reload",
    keywords: ["reset", "clear", "pwa", "service worker", "cache", "stale"],
    contexts: ["palette.root"],
    palette: true,
  }),
  command({
    id: COMMAND_IDS.deleteChat,
    label: "Delete chat",
    description: "Permanently delete this chat and its files",
    group: "danger",
    icon: "delete",
    keywords: ["remove", "trash"],
    contexts: ["palette.root"],
    destructive: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.deleteFolder,
    label: "Delete folder",
    description: "Permanently delete this folder and its chats",
    group: "danger",
    icon: "delete",
    keywords: ["remove", "trash", "project"],
    contexts: ["palette.root"],
    destructive: true,
    palette: true,
  }),
  command({
    id: COMMAND_IDS.toggleChatEdit,
    label: "Edit chats",
    description: "Enter or leave bulk chat selection",
    group: "chat-management",
    icon: "chat",
    keywords: ["select", "bulk", "manage", "done"],
    contexts: ["chat-search.browse", "chat-search.edit"],
    defaultBindings: [binding(stroke("KeyE", "E", ["primary"]))],
  }),
  command({
    id: COMMAND_IDS.renameHighlightedChat,
    label: "Rename highlighted chat",
    description: "Change the highlighted chat title",
    group: "chat-management",
    icon: "rename",
    keywords: ["rename", "title", "highlighted"],
    contexts: ["chat-search.browse"],
    defaultBindings: [
      binding(stroke("KeyR", "R", ["alt"])),
      binding(stroke("KeyK", "K", ["primary"]), stroke("KeyR", "R")),
    ],
  }),
  command({
    id: COMMAND_IDS.moveHighlightedChat,
    label: "Move highlighted chat",
    description: "Move the highlighted chat to another folder",
    group: "chat-management",
    icon: "move",
    keywords: ["move", "folder", "highlighted"],
    contexts: ["chat-search.browse"],
    defaultBindings: [
      binding(stroke("KeyK", "K", ["primary"]), stroke("KeyM", "M")),
    ],
  }),
  command({
    id: COMMAND_IDS.deleteHighlightedChat,
    label: "Delete highlighted chat",
    description: "Delete the highlighted chat after confirmation",
    group: "chat-management",
    icon: "delete",
    keywords: ["delete", "remove", "highlighted"],
    contexts: ["chat-search.browse"],
    defaultBindings: [
      binding(stroke("KeyK", "K", ["primary"]), stroke("KeyD", "D")),
    ],
    destructive: true,
  }),
  command({
    id: COMMAND_IDS.moveSelectedChats,
    label: "Move selected chats",
    description: "Move all selected chats to another folder",
    group: "chat-management",
    icon: "move",
    keywords: ["move", "bulk", "selected"],
    contexts: ["chat-search.edit"],
    defaultBindings: [binding(stroke("KeyM", "M"))],
  }),
  command({
    id: COMMAND_IDS.deleteSelectedChats,
    label: "Delete selected chats",
    description: "Delete all selected chats after confirmation",
    group: "chat-management",
    icon: "delete",
    keywords: ["delete", "remove", "bulk", "selected"],
    contexts: ["chat-search.edit"],
    defaultBindings: [
      binding(stroke("KeyD", "D")),
      binding(stroke("Delete", "Delete")),
    ],
    destructive: true,
  }),
];

export function commandLabel(id: string) {
  return commandRegistry.find((item) => item.id === id)?.label || id;
}

const commandById = new Map(commandRegistry.map((definition) => [definition.id, definition]));

export function getCommandDefinition(commandId: string): ShortcutCommandDefinition {
  const definition = commandById.get(commandId);
  if (!definition) throw new Error(`Unknown command: ${commandId}`);
  return definition;
}

export const paletteStableCommandIds = commandRegistry
  .filter((definition) => definition.palette)
  .map((definition) => definition.id);
