import crypto from "node:crypto";
import { execFile as execFileCallback } from "node:child_process";
import { EventEmitter } from "node:events";
import fs from "node:fs/promises";
import path from "node:path";
import { StringDecoder } from "node:string_decoder";
import { promisify } from "node:util";
import nodePty from "node-pty";
import { terminalSocketName } from "../../scripts/terminal-lifecycle.mjs";

const execFileAsync = promisify(execFileCallback);

export const PTY_MAX_SESSIONS = 32;
export const PTY_MAX_INPUT_BYTES = 4 * 1024 * 1024;
export const PTY_TMUX_MIN_VERSION = [3, 3];

const TEMPLATES = {
  shell: {
    title: "Shell",
    command: process.platform === "win32" ? "powershell.exe" : process.env.SHELL || "/bin/sh",
    args: process.platform === "win32" ? [] : ["-l"],
  },
};

const TMUX_CONFIG = `# Generated by Conduit. This tmux server is invisible session infrastructure.
set -g status off
set -g prefix None
set -g prefix2 None
set -g default-terminal "tmux-256color"
set -s escape-time 10
set -s extended-keys on
set -s set-clipboard on
set -as terminal-features ",xterm-256color:RGB:clipboard:focus:extkeys:sync"
set -g focus-events on
set -g mouse off
set -g set-titles off
set -wg automatic-rename off
set -wg allow-passthrough on
set -wg history-limit 10000
set -wg window-size latest
set -wg remain-on-exit off
`;

function failure(code, message) {
  return Object.assign(new Error(message), { code });
}

function view(record) {
  return {
    id: record.id,
    projectId: record.projectId,
    templateId: record.templateId,
    title: record.title,
    status: record.status,
    createdAt: record.createdAt,
    updatedAt: record.updatedAt,
    exitCode: record.exitCode ?? null,
    signal: record.signal ?? null,
  };
}

function nextTerminalTitle(records, projectId, baseTitle) {
  const used = new Set(records
    .filter((item) => item.projectId === projectId && item.status === "running")
    .map((item) => item.title));
  let title = baseTitle;
  let suffix = 2;
  while (used.has(title)) {
    title = `${baseTitle} ${suffix}`;
    suffix += 1;
  }
  return title;
}

function boundedDimension(value, fallback) {
  const next = Math.trunc(Number(value));
  return Number.isInteger(next) && next >= 1 && next <= 500 ? next : fallback;
}

function cleanEnvironment(source = process.env) {
  const env = { ...source, TERM: "xterm-256color", COLORTERM: "truecolor" };
  delete env.TMUX;
  delete env.TMUX_PANE;
  delete env.NO_COLOR;
  return env;
}

function parseTmuxVersion(value) {
  const match = String(value || "").match(/tmux\s+(\d+)\.(\d+)/i);
  return match ? [Number(match[1]), Number(match[2])] : null;
}

function versionAtLeast(actual, minimum) {
  return Boolean(actual && (actual[0] > minimum[0] || (actual[0] === minimum[0] && actual[1] >= minimum[1])));
}

function terminalSessionName(id) {
  return `c_${String(id).replace(/[^a-zA-Z0-9]/g, "")}`;
}

export class PtyManager extends EventEmitter {
  constructor({
    filePath,
    maxSessions = PTY_MAX_SESSIONS,
    pty = nodePty,
    tmuxPath = process.env.CONDUIT_TMUX_PATH || "tmux",
    run = (command, args, options) => execFileAsync(command, args, options),
  }) {
    super();
    this.filePath = filePath;
    this.maxSessions = maxSessions;
    this.pty = pty;
    this.tmuxPath = tmuxPath;
    this.run = run;
    this.records = new Map();
    // One disposable tmux client may own a terminal at a time. Different
    // terminal ids remain completely independent and may stream concurrently.
    this.attachments = new Map();
    this.persistQueue = Promise.resolve();
    this.createQueue = Promise.resolve();
    this.tmuxReady = false;
    this.stopping = false;
    this.tmuxSocketName = terminalSocketName(filePath);
    this.tmuxConfigPath = `${filePath}.tmux.conf`;
  }

  tmuxArgs(...args) {
    return ["-L", this.tmuxSocketName, "-f", this.tmuxConfigPath, ...args];
  }

  async invokeTmux(args, { tolerateMissingServer = false } = {}) {
    try {
      return await this.run(this.tmuxPath, this.tmuxArgs(...args), { env: cleanEnvironment(), maxBuffer: 1024 * 1024 });
    } catch (error) {
      const detail = String(error?.stderr || error?.message || "");
      if (tolerateMissingServer && /no server running|can't find session|no sessions|error connecting to .+ \(No such file or directory\)/i.test(detail)) return null;
      if (error?.code === "ENOENT") throw failure("pty_tmux_unavailable", "tmux 3.3 or newer is required for Workspace terminals");
      throw error;
    }
  }

  async ensureTmux() {
    if (this.tmuxReady) return;
    let version;
    try {
      const result = await this.run(this.tmuxPath, ["-V"], { env: cleanEnvironment(), maxBuffer: 64 * 1024 });
      version = parseTmuxVersion(result?.stdout);
    } catch (error) {
      if (error?.code === "ENOENT") throw failure("pty_tmux_unavailable", "tmux 3.3 or newer is required for Workspace terminals");
      throw error;
    }
    if (!versionAtLeast(version, PTY_TMUX_MIN_VERSION)) {
      throw failure("pty_tmux_version", `tmux ${PTY_TMUX_MIN_VERSION.join(".")} or newer is required for Workspace terminals`);
    }
    await fs.mkdir(path.dirname(this.tmuxConfigPath), { recursive: true });
    await fs.writeFile(this.tmuxConfigPath, TMUX_CONFIG, { encoding: "utf8", mode: 0o600 });
    await fs.chmod(this.tmuxConfigPath, 0o600);
    this.tmuxReady = true;
  }

  async load() {
    let persisted = { version: 2, sessions: [] };
    try { persisted = JSON.parse(await fs.readFile(this.filePath, "utf8")); }
    catch (error) { if (error.code !== "ENOENT") throw error; }

    // The product persistence promise is browser/network detach, not Conduit
    // server restart. Clean up a stale dedicated tmux server from a prior run
    // before projecting persisted rows as exited diagnostics.
    try {
      await this.ensureTmux();
      await this.invokeTmux(["kill-server"], { tolerateMissingServer: true });
    } catch (error) {
      if (error?.code !== "pty_tmux_unavailable" && error?.code !== "pty_tmux_version") throw error;
      this.tmuxReady = false;
    }

    for (const item of Array.isArray(persisted.sessions) ? persisted.sessions : []) {
      if (!item?.id || !item.projectId || !TEMPLATES[item.templateId]) continue;
      this.records.set(item.id, item.status === "running"
        ? {
          ...item,
          status: "exited",
          exitCode: null,
          signal: "server_restart",
          updatedAt: new Date().toISOString(),
        }
        : { ...item, status: "exited" });
    }
    await this.persist();
    return this.list();
  }

  list() { return [...this.records.values()].map(view).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  get(id) { const record = this.records.get(id); return record ? view(record) : null; }

  async activeSessionNames() {
    if (![...this.records.values()].some((item) => item.status === "running")) return new Set();
    await this.ensureTmux();
    const result = await this.invokeTmux(["list-sessions", "-F", "#{session_name}"], { tolerateMissingServer: true });
    return new Set(String(result?.stdout || "").split(/\r?\n/).filter(Boolean));
  }

  async reconcile() {
    const running = [...this.records.values()].filter((item) => item.status === "running");
    if (!running.length || this.stopping) return this.list();
    // A missing dedicated server legitimately means every tracked session is
    // gone. Other tmux failures are operational errors and must not silently
    // rewrite every running terminal as exited.
    const names = await this.activeSessionNames();
    let changed = false;
    for (const record of running) {
      if (names.has(record.tmuxSession || terminalSessionName(record.id))) continue;
      record.status = "exited";
      record.exitCode = 0;
      record.signal = "tmux_session_ended";
      record.updatedAt = new Date().toISOString();
      changed = true;
      this.emit("exit", view(record));
    }
    if (changed) await this.persist();
    return this.list();
  }

  create(options) {
    const operation = this.createQueue.then(
      () => this.createSerialized(options),
      () => this.createSerialized(options),
    );
    this.createQueue = operation.catch(() => {});
    return operation;
  }

  async createSerialized({ project, cwd, templateId = "shell", cols = 80, rows = 24 }) {
    const template = TEMPLATES[templateId];
    if (!template) throw failure("pty_template_not_allowed", "That terminal template is not available");
    if (!project?.id) throw failure("pty_project_required", "A terminal must belong to a project");
    if (!cwd || !path.isAbsolute(cwd)) throw failure("pty_cwd_required", "Terminal working directory is unavailable");
    let cwdStat;
    try { cwdStat = await fs.stat(cwd); }
    catch (error) {
      if (error.code === "ENOENT") throw failure("pty_cwd_unavailable", "Terminal working directory does not exist on this server");
      throw error;
    }
    if (!cwdStat.isDirectory()) throw failure("pty_cwd_unavailable", "Terminal working directory is not a directory");

    await this.reconcile();
    if ([...this.records.values()].filter((item) => item.status === "running").length >= this.maxSessions) {
      throw failure("pty_capacity_reached", "The terminal session limit has been reached");
    }
    await this.ensureTmux();

    const width = boundedDimension(cols, 80);
    const height = boundedDimension(rows, 24);
    const id = crypto.randomUUID();
    const tmuxSession = terminalSessionName(id);
    const now = new Date().toISOString();
    const title = nextTerminalTitle([...this.records.values()], project.id, template.title);
    const args = [
      "new-session", "-d", "-s", tmuxSession, "-c", cwd,
      "-x", String(width), "-y", String(height),
      template.command, ...template.args,
    ];
    await this.invokeTmux(args);

    const record = {
      id, projectId: project.id, templateId, title, status: "running",
      createdAt: now, updatedAt: now, exitCode: null, signal: null,
      tmuxSession,
    };
    this.records.set(id, record);
    await this.persist();
    this.emit("created", view(record));
    return view(record);
  }

  async attach(id, { cols = 80, rows = 24 } = {}) {
    const record = this.records.get(id);
    if (!record) throw failure("pty_not_found", "Terminal was not found");
    if (record.status !== "running") throw failure("pty_not_running", "Terminal is not running");
    if (this.attachments.has(id)) throw failure("pty_in_use", "Terminal is attached in another Conduit client");

    // Reserve before any asynchronous tmux work. This closes the attach/attach
    // race without introducing a global streaming lease.
    const lease = { state: "attaching", handle: null, cancelled: false };
    this.attachments.set(id, lease);
    try {
      await this.ensureTmux();
      const names = await this.activeSessionNames();
      if (this.attachments.get(id) !== lease || lease.cancelled) throw failure("pty_not_running", "Terminal is no longer available");
      if (!names.has(record.tmuxSession || terminalSessionName(id))) {
        this.attachments.delete(id);
        await this.reconcile();
        throw failure("pty_not_running", "Terminal is no longer running");
      }

      const width = boundedDimension(cols, 80);
      const height = boundedDimension(rows, 24);
      const tmuxSession = record.tmuxSession || terminalSessionName(id);
      const handle = this.pty.spawn(
        this.tmuxPath,
        this.tmuxArgs("-u", "attach-session", "-t", tmuxSession),
        {
          name: "xterm-256color",
          cols: width,
          rows: height,
          cwd: process.cwd(),
          env: cleanEnvironment(),
        },
      );
      lease.handle = handle;
      lease.state = "attached";
      if (this.attachments.get(id) !== lease || lease.cancelled) {
        try { handle.kill(); } catch {}
        throw failure("pty_not_running", "Terminal is no longer available");
      }

      let exited = false;
      let exitEvent = null;
      const inputDecoder = new StringDecoder("utf8");
      const exitListeners = new Set();
      const dataListeners = new Set();
      const earlyData = [];
      handle.onData((value) => {
        // tmux may redraw immediately after attach. Do not lose that authoritative
        // initial screen in the small interval before terminal-stream subscribes.
        if (!dataListeners.size) earlyData.push(value);
        else for (const listener of dataListeners) listener(value);
      });
      handle.onExit((event) => {
        if (exited) return;
        exited = true;
        exitEvent = event;
        if (this.attachments.get(id) === lease) this.attachments.delete(id);
        for (const listener of exitListeners) listener(event);
        if (!this.stopping) void this.reconcile().catch(() => {});
      });

      return {
        onData(listener) {
          dataListeners.add(listener);
          if (earlyData.length) {
            for (const value of earlyData.splice(0)) listener(value);
          }
          return () => dataListeners.delete(listener);
        },
        onExit(listener) {
          exitListeners.add(listener);
          if (exitEvent) queueMicrotask(() => { if (exitListeners.has(listener)) listener(exitEvent); });
          return () => exitListeners.delete(listener);
        },
        write(bytes) {
          const value = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes);
          if (value.length > PTY_MAX_INPUT_BYTES) throw failure("pty_input_too_large", `Terminal input exceeds ${PTY_MAX_INPUT_BYTES} bytes`);
          if (!exited) {
            const decoded = inputDecoder.write(value);
            if (decoded) handle.write(decoded);
          }
        },
        resize(nextCols, nextRows) {
          if (!exited) handle.resize(boundedDimension(nextCols, width), boundedDimension(nextRows, height));
        },
        kill() {
          if (exited) return;
          try { handle.kill(); } catch {}
        },
      };
    } catch (error) {
      if (this.attachments.get(id) === lease) this.attachments.delete(id);
      throw error;
    }
  }

  async rename(id, title) {
    const record = this.records.get(id);
    if (!record) throw failure("pty_not_found", "Terminal was not found");
    const next = String(title || "").trim();
    if (!next || next.length > 80) throw failure("pty_title_invalid", "Terminal title must be between 1 and 80 characters");
    record.title = next;
    record.updatedAt = new Date().toISOString();
    await this.persist();
    this.emit("updated", view(record));
    return view(record);
  }

  async killTmuxSession(record) {
    if (!record?.tmuxSession && !record?.id) return;
    try {
      await this.ensureTmux();
      await this.invokeTmux(["kill-session", "-t", record.tmuxSession || terminalSessionName(record.id)], { tolerateMissingServer: true });
    } catch (error) {
      if (error?.code !== "pty_tmux_unavailable" && error?.code !== "pty_tmux_version") throw error;
    }
  }

  killAttachment(id) {
    const lease = this.attachments.get(id);
    if (!lease) return;
    lease.cancelled = true;
    try { lease.handle?.kill(); } catch {}
    if (this.attachments.get(id) === lease) this.attachments.delete(id);
  }

  async remove(id) {
    const record = this.records.get(id);
    if (!record) return false;

    // A destruction sentinel blocks a new attach until the tmux session has
    // actually been removed, including when removal races an in-flight attach.
    const previous = this.attachments.get(id);
    if (previous) {
      previous.cancelled = true;
      try { previous.handle?.kill(); } catch {}
    }
    const removalLease = { state: "destroying", handle: null, cancelled: true };
    this.attachments.set(id, removalLease);
    try {
      if (record.status === "running") await this.killTmuxSession(record);
      this.records.delete(id);
      await this.persist();
      this.emit("removed", { id, projectId: record.projectId });
      return true;
    } finally {
      if (this.attachments.get(id) === removalLease) this.attachments.delete(id);
    }
  }

  async removeProject(projectId) {
    const records = [...this.records.values()].filter((item) => item.projectId === projectId);
    for (const record of records) await this.remove(record.id);
    return records.length;
  }

  async stopAll() {
    this.stopping = true;
    for (const id of [...this.attachments.keys()]) this.killAttachment(id);
    try {
      if (this.tmuxReady || [...this.records.values()].some((item) => item.status === "running")) {
        await this.ensureTmux();
        await this.invokeTmux(["kill-server"], { tolerateMissingServer: true });
      }
    } catch (error) {
      if (error?.code !== "pty_tmux_unavailable" && error?.code !== "pty_tmux_version") throw error;
    }
  }

  persist() {
    const payload = JSON.stringify({ version: 2, sessions: [...this.records.values()] }, null, 2) + "\n";
    const write = async () => {
      await fs.mkdir(path.dirname(this.filePath), { recursive: true });
      const tempPath = `${this.filePath}.tmp-${process.pid}-${crypto.randomBytes(6).toString("hex")}`;
      try {
        await fs.writeFile(tempPath, payload, { encoding: "utf8", mode: 0o600 });
        await fs.chmod(tempPath, 0o600);
        await fs.rename(tempPath, this.filePath);
        await fs.chmod(this.filePath, 0o600);
      } finally {
        await fs.rm(tempPath, { force: true }).catch(() => {});
      }
    };
    this.persistQueue = this.persistQueue.then(write, write);
    return this.persistQueue;
  }
}
